# Generated by Django 5.0.7 on 2025-04-23 05:00

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус вакансии',
                'verbose_name_plural': 'Статусы вакансий',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('department', models.CharField(choices=[('MKT', 'Маркетинг'), ('SLS', 'Продажи'), ('FIN', 'Финансы'), ('IT', 'Информационные технологии'), ('HR', 'Управление персоналом'), ('RND', 'Исследования и разработка'), ('PRD', 'Производство'), ('LOG', 'Логистика'), ('LEG', 'Юридический отдел'), ('ADM', 'Администрация'), ('QA', 'Контроль качества'), ('SEC', 'Безопасность'), ('CS', 'Обслуживание клиентов')], max_length=255, verbose_name='Отдел')),
                ('city', models.CharField(choices=[('BSK', 'Бишкек'), ('OSH', 'Ош'), ('JBD', 'Джалал-Абад'), ('KKL', 'Каракол'), ('TKM', 'Токмок'), ('NRN', 'Нарын'), ('TLS', 'Талас'), ('BTK', 'Баткен'), ('BLC', 'Балыкчы'), ('KBL', 'Кара-Балта'), ('KNT', 'Кант'), ('KMN', 'Кемин'), ('ISF', 'Исфана'), ('CPA', 'Чолпон-Ата'), ('UZG', 'Узген'), ('KKY', 'Кызыл-Кия'), ('SLK', 'Сулюкта'), ('KSU', 'Кара-Суу'), ('ATB', 'Ат-Баши'), ('TKT', 'Токтогул')], max_length=255, verbose_name='Город')),
                ('priority', models.CharField(choices=[('P1', 'Срочный'), ('P2', 'Высокий'), ('P3', 'Нормальный'), ('P4', 'Низкий'), ('P5', 'Наименьший')], max_length=255, verbose_name='Приоритет')),
                ('requirements', ckeditor.fields.RichTextField(verbose_name='Требования к вакансии')),
                ('responsibilities', ckeditor.fields.RichTextField(verbose_name='Обязанности кандидата')),
                ('min_salary', models.IntegerField(verbose_name='Минимальная зарплата')),
                ('max_salary', models.IntegerField(verbose_name='Максимальная зарплата')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата открытия')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('time_to_offer', models.DurationField(blank=True, null=True, verbose_name='Понадобившееся время')),
                ('department_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dl_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rc_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Рекрутер')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancy.vacancystatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
