# Generated by Django 5.0.7 on 2025-04-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Статус')),
                ('is_default', models.BooleanField(default=False, verbose_name='Статус по умолчанию')),
            ],
            options={
                'verbose_name': 'Статус вакансии',
                'verbose_name_plural': 'Статусы вакансий',
            },
        ),
    ]
