# Generated by Django 5.0.7 on 2025-04-23 11:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancystatus',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Статус по умолчанию'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=ckeditor.fields.RichTextField(verbose_name='Требования к кандидату'),
        ),
    ]
