# Generated by Django 5.0.7 on 2025-05-04 14:33

from django.db import migrations
from django.db.migrations import RunPython


def get_default_status(apps, schema_editor):
    vacancy_status = apps.get_model("vacancy", "VacancyStatus")
    db_alias = schema_editor.connection.alias

    default_status_name = "На рассмотрении"
    status_obj, created = vacancy_status.objects.using(db_alias).get_or_create(
        name=default_status_name,
        defaults={
            'is_default': True,
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        RunPython(get_default_status, migrations.RunPython.noop),
    ]
