# Generated by Django 5.0.7 on 2025-04-23 11:05

from django.db import migrations


def create_statuses(apps, schema_editor):
    VacancyStatus = apps.get_model('vacancy', 'VacancyStatus')
    VacancyStatus.objects.get_or_create(name="На рассмотрении", is_default=True)

class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancystatus_is_default_alter_vacancy_requirements'),
    ]

    operations = [migrations.RunPython(create_statuses)]
