# Generated by Django 5.0.7 on 2025-04-23 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_create_default_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancy.vacancystatus', verbose_name='Статус'),
        ),
    ]
