# Generated by Django 5.0.7 on 2025-05-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_alter_vacancy_vacancy_request_vacancycomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancystatus',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Отметьте, если этот статус означает завершение работы по вакансии', verbose_name='Является закрытым статусом'),
        ),
        migrations.AddField(
            model_name='vacancystatus',
            name='is_opened',
            field=models.BooleanField(default=False, help_text='Отметьте, если при переходе в этот статус нужно установить дату началаработы', verbose_name='Триггер даты открытия'),
        ),
    ]
