# Generated by Django 5.0.7 on 2025-05-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_vacancystatus_is_closed_vacancystatus_is_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(verbose_name='Требования к кандидату'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(verbose_name='Обязанности кандидата'),
        ),
        migrations.AlterField(
            model_name='vacancystatus',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Отметьте, если при переходе в этот статус нужно установить дату начала', verbose_name='Является закрытым статусом'),
        ),
    ]
