# Generated by Django 5.0.7 on 2025-05-09 08:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_alter_vacancyhistorychange_new_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacancyHistoryChange',
            new_name='VacancyChangeHistory',
        ),
    ]
