# Generated by Django 4.2 on 2025-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_alter_candidatesource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetag',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
