# Generated by Django 5.0.7 on 2025-05-04 14:33

from django.db import migrations
from django.db.migrations import RunPython


def get_or_create_default_objects(apps, schema_editor):
    CandidateSource = apps.get_model("candidate", "CandidateSource")
    CandidateTag = apps.get_model("candidate", "CandidateTag")
    CandidateApplicationStatus = apps.get_model("candidate", "CandidateApplicationStatus")

    db_alias = schema_editor.connection.alias

    sources = [
        "hh.ru",
        "Linkedin",
        "devKG",
        "Рекомендация",
        "Прямой отклик",
    ]

    for name in sources:
        CandidateSource.objects.using(db_alias).get_or_create(name=name)

    tags = [
        "Python",
        "Django",
        "JavaScript",
        "React",
        "PostgreSQL",
        "Frontend",
        "Backend",
        "DevOps",
        "UI/UX",
        "Java",
        "Linux",
    ]

    for title in tags:
        CandidateTag.objects.using(db_alias).get_or_create(title=title)

    statuses = [
        {"name": "Новая заявка", "order": 1, "is_default": True, "is_rejected": False, "is_success": False},
        {"name": "Тестовое задание", "order": 3, "is_default": False, "is_rejected": False, "is_success": False},
        {"name": "Интервью с HR", "order": 4, "is_default": False, "is_rejected": False, "is_success": False},
        {"name": "Техническое интервью", "order": 5, "is_default": False, "is_rejected": False, "is_success": False},
        {"name": "Предложение", "order": 6, "is_default": False, "is_rejected": False, "is_success": False},
        {"name": "Принят", "order": 7, "is_default": False, "is_rejected": False, "is_success": True},
        {"name": "Отказ", "order": 8, "is_default": False, "is_rejected": True, "is_success": False},
        {"name": "Отказался сам", "order": 9, "is_default": False, "is_rejected": True, "is_success": False},
    ]

    for status in statuses:
        CandidateApplicationStatus.objects.using(db_alias).get_or_create(
            name=status["name"],
            defaults={
                "order": status["order"],
                "is_default": status["is_default"],
                "is_rejected": status["is_rejected"],
                "is_success": status["is_success"],
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_alter_candidatesource_name'),
    ]

    operations = [
        RunPython(get_or_create_default_objects, migrations.RunPython.noop),
    ]
