# Generated by Django 5.0.7 on 2025-05-08 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_request', '0002_alter_vacancyrequest_requirements_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancyrequestcomment',
            options={'verbose_name': 'Комментарий к Заявке на подбор', 'verbose_name_plural': 'Комментарии к Заявкам на подбор'},
        ),
        migrations.CreateModel(
            name='VacancyRequestChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(max_length=50, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=50, verbose_name='Новый статус')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='vacancy_request.vacancyrequest')),
            ],
            options={
                'verbose_name': 'История изменений к Заявке на подбор',
                'verbose_name_plural': 'Истории изменений к Заявкам на подбор',
            },
        ),
    ]
