# Generated by Django 5.0.7 on 2025-04-29 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_vacancyrequest_vacancy'),
        ('vacancy_request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vacancy', to='vacancy_request.vacancyrequest', verbose_name='Исходная заявка'),
        ),
        migrations.CreateModel(
            name='VacancyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='vacancy.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='VacancyRequest',
        ),
    ]
