# Generated by Django 5.0.7 on 2025-05-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_alter_vacancy_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancystatus',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Отметьте, если этот статус завершает работу по вакансии (найм/отмена) и требует установки даты закрытия (`closed_at`)', verbose_name='Финальный (закрытый) статус?'),
        ),
        migrations.AlterField(
            model_name='vacancystatus',
            name='is_opened',
            field=models.BooleanField(default=False, help_text='Отметьте, если этот статус означает начало активной работы по вакансии (для установки даты `opened_at`)', verbose_name='Статус активной работы?'),
        ),
    ]
