# Generated by Django 5.0.7 on 2025-05-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0008_alter_vacancycomment_options_vacancyhistorychange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyhistorychange',
            name='new_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='vacancyhistorychange',
            name='old_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Старый статус'),
        ),
    ]
