# Generated by Django 5.0.7 on 2025-05-05 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancy', '0007_alter_vacancystatus_is_closed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Статус')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Статус означает отказ кандидату?')),
                ('is_success', models.BooleanField(default=False, verbose_name='Статус означает, что успешный найм?')),
                ('order', models.IntegerField(unique=True, verbose_name='Очередность')),
            ],
            options={
                'verbose_name': 'Статус кандидата в вакансии',
                'verbose_name_plural': 'Статусы кандидата в вакансии',
            },
        ),
        migrations.CreateModel(
            name='CandidateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Например: hh.ru, linkedin', max_length=100, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источник',
            },
        ),
        migrations.CreateModel(
            name='CandidateTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume', verbose_name='Резюме')),
                ('city', models.CharField(blank=True, choices=[('BSK', 'Бишкек'), ('OSH', 'Ош'), ('JBD', 'Джалал-Абад'), ('KKL', 'Каракол'), ('TKM', 'Токмок'), ('NRN', 'Нарын'), ('TLS', 'Талас'), ('BTK', 'Баткен'), ('BLC', 'Балыкчы'), ('KBL', 'Кара-Балта'), ('KNT', 'Кант'), ('KMN', 'Кемин'), ('ISF', 'Исфана'), ('CPA', 'Чолпон-Ата'), ('UZG', 'Узген'), ('KKY', 'Кызыл-Кия'), ('SLK', 'Сулюкта'), ('KSU', 'Кара-Суу'), ('ATB', 'Ат-Баши'), ('TKT', 'Токтогул')], max_length=50, null=True, verbose_name='Локация')),
                ('experience', models.CharField(choices=[('JUNIOR', 'Младший'), ('MIDDLE', 'Средний'), ('SENIOR', 'Профессионал')], max_length=100, verbose_name='Опыт')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Сопроводительное письмо')),
                ('salary_expectation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зарплатные ожидания')),
                ('source_type', models.CharField(blank=True, choices=[('APPLICATION', 'Отклик на вакансию'), ('SOURCED', 'Найден рекрутером'), ('REFERRAL', 'Рекомендация'), ('INTERNAL', 'Внутренний кандидат'), ('UNSOLICITED', 'Самостоятельное обращение'), ('OTHER', 'Другое')], max_length=50, null=True, verbose_name='Тип отклика')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Добавлен пользователем')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
            },
        ),
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejected_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Причина отказа')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate', verbose_name='Кандидат')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Рекрутер')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy', verbose_name='Вакансия')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.candidateapplicationstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка кандидата на вакансию',
                'verbose_name_plural': 'Заявки кандидатов на вакансии',
                'unique_together': {('candidate', 'vacancy')},
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='vacancy',
            field=models.ManyToManyField(through='candidate.CandidateApplication', to='vacancy.vacancy'),
        ),
        migrations.CreateModel(
            name='CandidateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Заметка')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
        migrations.CreateModel(
            name='CandidateReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Текст')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Обратная связь по кандидату',
                'verbose_name_plural': 'Обратная связь по кандидатам',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.candidatesource', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='candidate.candidatetags', verbose_name='Теги'),
        ),
    ]
