# Generated by Django 5.0.7 on 2025-05-05 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('vacancy', '0007_alter_vacancystatus_is_closed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateTags',
            new_name='CandidateTag',
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidate.candidate', verbose_name='Кандидат'),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_applications', to=settings.AUTH_USER_MODEL, verbose_name='Рекрутер'),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='candidate.candidateapplicationstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancy.vacancy', verbose_name='Вакансия'),
        ),
    ]
