# Generated by Django 5.0.7 on 2025-05-09 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidateapplicationstatus_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplicationChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Старый статус')),
                ('new_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Новый статус')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='candidate.candidateapplication', verbose_name='Заявка кандидата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История изменения статуса заявки',
                'verbose_name_plural': 'История изменения статусов заявок',
            },
        ),
    ]
