# Generated by Django 5.0.7 on 2025-05-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_candidateapplicationchangehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesource',
            name='name',
            field=models.CharField(blank=True, help_text='Например: hh.ru, linkedin', max_length=100, null=True, verbose_name='Источник'),
        ),
    ]
