# Generated by Django 4.2 on 2025-05-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_alter_candidatetag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesource',
            name='name',
            field=models.CharField(blank=True, help_text='Например: hh.ru, linkedin', max_length=100, null=True, unique=True, verbose_name='Источник'),
        ),
    ]
