# Generated by Django 4.2 on 2025-05-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_alter_candidatesource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesource',
            name='name',
            field=models.CharField(default=1, help_text='Например: hh.ru, linkedin', max_length=100, unique=True, verbose_name='Источник'),
            preserve_default=False,
        ),
    ]
