# Generated by Django 5.0.7 on 2025-05-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyrequest',
            name='requirements',
            field=models.TextField(verbose_name='Требования к кандидату'),
        ),
        migrations.AlterField(
            model_name='vacancyrequest',
            name='responsibilities',
            field=models.TextField(verbose_name='Обязанности кандидата'),
        ),
    ]
